### ISSUE TITLE
Fix broken M_1_5_03

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#118]
Hi @Niels-NTG, could you fix this one at some time? Ran into it accidentally ... not urgent. Best, B

**Comment by Niels-NTG** [comment]
@b-g I've investigated it. Turns out that for reasons unknown to me, it works just fine if you open up index.html directly. It only breaks when you view it via the node JS server.

**Comment by nucliweb** [comment]
Hi @Niels-NTG & @b-g !

I see that when `help-tooltip.js` load `sketch.js` with `$.get('sketch.js', function(data) { ... });` *(https://github.com/generative-design/Code-Package-p5.js/blob/master/libraries/help-tooltip.js#L3)*, the call generate other `canvas` because generate other instance with `var myp5 = new p5(sketch);` *(https://github.com/generative-design/Code-Package-p5.js/blob/master/02_M/M_1_5_03/sketch.js#L81)*

<img width="960" alt="doble-canvas" src="https://user-images.githubusercontent.com/1307927/34906018-9c5f5f54-f864-11e7-89e8-80f3b8dd4644.png">

**This problem is in other samples.**

I sent a [PR 160](https://github.com/generative-design/Code-Package-p5.js/pull/160) to fix this problem.

**Comment by bohnacker** [comment]
Thanks @nucliweb! Works fine now.

**Comment by nucliweb** [comment]
🙌🏼

**Comment by b-g** [comment]
@nucliweb Yay + (we have been blind)! 🙏
