### ISSUE TITLE
P_2_2_5_01: Code is cool, but has to many new commands and structures

### ISSUE THREAD

**Issue by bohnacker** [generative-design/Code-Package-p5.js#128]
We should keep the code closer to the already learned commands. Of course, having the circles as Objects is a good way to do it, but is completely new for the reader at this point. That might be confusing.
Still, we could keep this kind of code for P_2_2_5_02.

**Comment by Niels-NTG** [comment]
I can definitely see what you mean. During the porting proces in the past months I've made an effort to not only do a verbatim translation from Java to JavaScript, but also utilise the power of JS where it made improvements to both performance and readability. I've also removed or changed things that just don't make much sense in JavaScript or are remnants of old versions of Processing (for example: `smooth();` is completely unnecessary since that's on by default since at least Processing 2). In JavaScript it's a lot easier to do OOP. Instead of having a dozen of arrays of the same length where the index has to be kept in sync, you can make an Array of objects that does the same thing with comparatively better performance, shorter overal size of the sketch and beter readability.

**Comment by Niels-NTG** [comment]
So basically what I'm saying is that we should find a good middle ground.

**Comment by bohnacker** [comment]
You're right, we should find a compromise. I'd opt for keeping the Circle object but replacing `forEach()`, `circles.some()`and `circles.find()`with simple for-loops. I know, it breaks the heart of a real javascript programmer, but from my experience even a simple for-loop is hard enough to understand for beginners.

**Comment by Niels-NTG** [comment]
I completely agree. I will make the appropriate changes to `P_2_2_5_01` and `P_2_2_5_02` ASAP. Also will look into changing this the new sketches I designed.

**Comment by Niels-NTG** [comment]
`forEach` is for iterating data, normal `for` loops are for iterating a range of numbers. I use `forEach` all the time whenever I write JavaScript. But this style where you pass functions isn't common in other mainstream programming languages, meaning that's not directly transferrable to another language. Also you have the complexity of scoping `this`, of which the working should not be in the _scope_ of the book.  To keep it simple for the reader, I'm in favour for picking a single style we use all throughout the book. And that's is probably a plain old `for` loop.

**Comment by bohnacker** [comment]
I wouldn't mind if there are some `forEach`s remaining in the examples. It's especially ok for all _02, _03, ... sketches. We explain the _01 sketches in the book, so these should be quite readable and understandable for beginners.

**Comment by bohnacker** [comment]
@Niels-NTG Did you already change something on this sketch? If not, I will just go on with that...
